package server

import (
	"context"
	"encoding/json"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/zer0d4y5/argus/internal/audit"
	"github.com/zer0d4y5/argus/internal/sbom"
)

// SBOM generation from the console (operator+). An SBOM is an artifact, not a
// run: it lists the components present in a filesystem target, so it applies
// to the served repo and to dir/git targets, never to cloud/DAST/image
// targets (which have no source tree). The document is generated by trivy and
// streamed back unmodified for the browser to download. Nothing is stored;
// the audit log records that a bill of materials was produced.

// sbomContentType and sbomFilenameExt map an SBOM format to the response
// content type and a friendly download extension.
func sbomContentType(f sbom.Format) string {
	switch f {
	case sbom.CycloneDX:
		return "application/vnd.cyclonedx+json"
	case sbom.SPDXJSON:
		return "application/spdx+json"
	default: // SPDXTag
		return "text/plain; charset=utf-8"
	}
}

func sbomFilenameExt(f sbom.Format) string {
	switch f {
	case sbom.CycloneDX:
		return "cdx.json"
	case sbom.SPDXJSON:
		return "spdx.json"
	default:
		return "spdx.txt"
	}
}

// handleSBOM is POST /api/sbom {targetId?, format?}. An empty targetId means
// the served repo. The response body IS the SBOM document (for a blob
// download), so errors are JSON but success is the raw artifact.
func (s *Server) handleSBOM(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeErr(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}
	var req struct {
		TargetID string `json:"targetId"`
		Format   string `json:"format"`
	}
	r.Body = http.MaxBytesReader(w, r.Body, 8192)
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeErr(w, http.StatusBadRequest, "invalid request body")
		return
	}
	format, err := sbom.ParseFormat(req.Format)
	if err != nil {
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	if !sbom.Available() {
		writeErr(w, http.StatusServiceUnavailable, "trivy not found on PATH: install trivy to generate an SBOM")
		return
	}

	// Resolve the filesystem root to inventory. The served repo is the
	// default; a registered target must be a filesystem kind (dir/git), never
	// a cloud/DAST/image target, which has no component tree.
	root := s.dir
	label := "repo"
	if req.TargetID != "" {
		if s.targets == nil {
			writeErr(w, http.StatusNotFound, "target not found")
			return
		}
		t, err := s.targets.Get(req.TargetID)
		if err != nil {
			writeErr(w, http.StatusNotFound, "target not found")
			return
		}
		if _, nonFS := s.targets.NonFSRunStore(t); nonFS {
			writeErr(w, http.StatusBadRequest, t.Kind()+" targets have no component tree; an SBOM applies to directory and git targets only")
			return
		}
		root = s.targets.Root(t)
		if fi, err := os.Stat(root); err != nil || !fi.IsDir() {
			writeErr(w, http.StatusBadRequest, "target has no local tree yet: run a scan first to populate it")
			return
		}
		label = t.Name
	}

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Minute)
	defer cancel()
	doc, err := sbom.Generate(ctx, sbom.Options{Target: root, Format: format})
	if err != nil {
		writeErr(w, http.StatusBadGateway, err.Error())
		return
	}

	s.audit(audit.EventSbomGenerate, actorFrom(r), map[string]string{
		"target": targetOrRepo(req.TargetID),
		"format": string(format),
	})

	filename := "sbom-" + sanitizeFilename(label) + "." + sbomFilenameExt(format)
	w.Header().Set("Content-Type", sbomContentType(format))
	w.Header().Set("Content-Disposition", "attachment; filename=\""+filename+"\"")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.WriteHeader(http.StatusOK)
	w.Write(doc)
}

// targetOrRepo renders the audit target field.
func targetOrRepo(id string) string {
	if id == "" {
		return "repo"
	}
	return id
}

// sanitizeFilename reduces a target name to a safe download filename stem.
func sanitizeFilename(name string) string {
	safe := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
			return r
		default:
			return '-'
		}
	}, name)
	safe = strings.Trim(safe, "-")
	if safe == "" {
		return "target"
	}
	return safe
}
